### ISSUE TITLE
What does this adjustment do?

### ISSUE THREAD

**Issue by taralx** [gvinciguerra/PGM-index#13]
https://github.com/gvinciguerra/PGM-index/commit/e346995724dd12a7b0b5c039ec3475fe097cb54d added code that appears to add 1 to the end of a run of 2 or more equal values, so long as that wouldn't result in the new value creating or extending a run. But the title is "small fixes" and there isn't any comment. Can you help me understand what this is for?

**Comment by gvinciguerra** [comment]
Hi @taralx, it's a technical adjustment for when the input contains duplicate keys. Basically, at the end of a run of two or more equal keys, say a run `x=first[j]=first[j+1]=...=first[i-1]=first[i]`, if the next key `first[i+1]` is not equal to `x+1`, then we must construct the piecewise linear model so that values `x+1,x+2,...,first[i+1]-1` are approximated to a position `i`. If this adjustment is not applied, then the piecewise linear model is free to map the any query value in `x+1,x+2,...,first[i+1]-1` to a position `j ± ε`, which is wrong, because the `lower_bound` (i.e. the _successor_) of any value `x+1,x+2,...,first[i+1]-1` is at position `i`.

Note that this adjustment needs to be applied only at the bottommost level of the PGM because the segments' keys in upper levels are never repeated. Indeed, compare `in_fun` (which applies the adjustment when `flag==true==1`) at:
https://github.com/gvinciguerra/PGM-index/blob/6f4cda8d0ac7bf5d3ba15c9139af8a3f78ad5042/include/pgm/pgm_index.hpp#L110

with `in_fun_rec` (which doesn't have the adjustment) at:
https://github.com/gvinciguerra/PGM-index/blob/6f4cda8d0ac7bf5d3ba15c9139af8a3f78ad5042/include/pgm/pgm_index.hpp#L120

Hope this helps :)

**Comment by taralx** [comment]
So this happens because we map values to successors instead of predecessors?

**Comment by taralx** [comment]
Am I right in understanding that this only applies to duplicate keys because for unique keys `i = j` but with repeated keys you could have `i > j + ε`?

**Comment by gvinciguerra** [comment]
That's correct ;)

**Comment by taralx** [comment]
Thanks! Do you think it would be reasonable to add a comment to that section of code for other readers?

**Comment by gvinciguerra** [comment]
Agreed ;) 

Thanks @taralx
