### ISSUE TITLE
Application of PGM-index

### ISSUE THREAD

**Issue by authwork** [gvinciguerra/PGM-index#17]
Hi, this is a interesting work! Thanks for your contribution.

But I have some problems:
1. in the examples, we can see it trains a map function from "Key" (the value of key) to its stored positions. If we really want to use it in real example: the user want to access the value based on the key. Then how values should be organzed with PGM-index? In other words, many (key, value) pairs are stored in a large array and sorted by key (maybe a value is a pointer or offset, etc. It suggests the length of key and value is almost fixed). How to make full use of PGM-index to search a key and return the corresponding value? I believe it should find the position, and then use (position + the length of key) to return the value. However, PGM-index seems need significant upgrade to support this function. Is there any other solutions?

2. In the paper, it seems "works for any kind of keys that can be mapped to reals while preserving their order. Examples include integers, strings, etc." is very difficult to understand and hard to make implementation. My reasons are given below:
    - issue one: the function of map is to map a key (string) to a real, and then use the sorted reals to construct PGM-index and find the offset? Why not I directly map the key to its offset or value. Since the mapping between keys and reals is acceptable, then mapping between keys and offsets (values) should also be acceptable.
    - issue two: One important thing is that how string (key type in may DB) can be support in current system. As you can see, a string could have unlimited length. It should be very hard to bound the errors, especially when many short fixed-length strings mixed with a few long strings appears. I also refer to the #8, this hint is very nice, but other issues come out: map string directly to uint128_t at bit-level (maybe) can solve the issue one, but it caused: (1) the max length of string is 24 (?) (2) the wasted space, said some strings have 19 chars, and it can only use uint128_t to do the map. some spaces is wasted then.

**Comment by gvinciguerra** [comment]
Hi @authwork and thanks for your interest!

Let me first answer your point 1. I assume that you refer to the `PGMIndex` class (and the variants `CompressedPGMIndex`, `OneLevelPGMIndex`, `BucketingPGMIndex`, `EliasFanoPGMIndex`) because there are also `DynamicPGMIndex`, which is an updatable key-value container, and `MultidimensionalPGMIndex` for n-dimensional points, which both take care of the data storage for you.

The abstraction that the `PGMIndex` class provides is that of an index structure which is **separate** from the data storage. This way, the programmers are free to keep the data in any storage device (memory, disk, remote disk, ...) and memory layout (contiguous keys in a malloc'd area, key-value pairs via [AoS or SoA](https://en.wikipedia.org/wiki/AoS_and_SoA), logical database pages, ...) they want.

About your example on key-value pairs, suppose that a programmer has chosen this data layout:

```cpp
struct MyKeyVal {
    uint32_t key;
    std::string val;
    operator uint32_t() const { return key; }
};

std::vector<MyKeyVal> data = {{2, "a"}, {3, "b"}, {5, "c"}, {6, "d"}, {8, "a"}, {10, "b"}};
```

Then, the PGM can be used "as-is" as follows:

```cpp
pgm::PGMIndex<decltype(MyKeyVal::key), 8> pgm(data.begin(), data.end());

auto q = 6;
auto range = pgm.search(q);
std::cout << std::lower_bound(data.begin() + range.lo, data.begin() + range.hi, q)->val; // outputs "d"
```

Later, if the `data` vector has grown too big to be kept in memory, the programmer could move the string values to a file `f` and store an `offset` inside `MyKeyVal` instead of `val`. Then, the last line in the code above could become something like:

```cpp
auto offset  = std::lower_bound(data.begin() + range.lo, data.begin() + range.hi, q)->offset;
std::cout << f.retrieve_string_at(offset);
```

Again, without modifying anything inside the PGM-index library.

Hope this helps 😉

**Comment by authwork** [comment]
Many thanks for your suggestions, I will have a try. 👍

**Comment by gvinciguerra** [comment]
Happy to help 😉

For your second point/issue one, I'd like to point you out to _order-preserving minimal perfect hash functions_, which solve the problem you described.

For your second point/issue two, I believe that handling strings in this way is far from being adequate if compared to prefix-search data structures made for variable-length strings, i.e. tries (I made the same comment [elsewhere](https://news.ycombinator.com/item?id=25902859)).
Still, if one wants to persevere with the PGM, note that apart from the sorted strings there's no need to physically store the mapping (e.g. via an array of 128-bit ints), i.e. there is no waste of space. Indeed, it is sufficient to construct the PGM so that it "sees" just the fixed-length prefix of each string. This way, the PGM is guaranteed to find the first string having a prefix matching the given query string's prefix. Then, you can scan (or [exponential search](https://en.wikipedia.org/wiki/Exponential_search) on) the neighbouring strings to find the one you are looking for.

Hope this helps too.

**Comment by authwork** [comment]
Many thanks for your explanation, it is more clear now.

It will be better if you can add an example to help readers to understand it.

For instance, in the above case:
```cpp
struct MyKeyVal {
    std::string key;
    std::string val;
    operator std::string() const { return key; }
};
```
Should we do the following steps:
```cpp
1. sort the array of MyKeyVal based on the key
2. turn the key (std::string) into the uint32_t by using order-preserving minimal perfect hash functions.
     1) for long key string, we only turn its prefix to uint32_t 
     2) for multiple key strings share the same prefix, we do a second-level search.
......
```

**Comment by gvinciguerra** [comment]
Again, I have to **advise against not using tries** (or hashing if you only do exact string lookups), but if you want a proof-of-concept here it is:

```cpp
template <typename T>
T str_to_t(const std::string &s) {
    T x = 0;
    for (auto i = 0; i < std::min(s.length(), sizeof(T)); ++i)
        x |= T(s[i]) << (8 * (sizeof(T) - i - 1));
    return x;
}

struct MyKeyVal {
    std::string key;
    std::string val;
    operator __uint128_t() const { return str_to_t<__int128_t>(key); }
    bool operator<(const std::string &s) const { return key < s; }
};

...

std::vector<MyKeyVal> data = {{"a", ""}, {"aa", ""}, {"baa", ""}, {"bab", ""}, {"baba", ""}, {"cccc", ""}};
pgm::PGMIndex<__uint128_t, 8> pgm(data.begin(), data.end());

auto q = "bab";
auto range = pgm.search(str_to_t<__uint128_t>(q));
std::cout << std::lower_bound(data.begin() + range.lo, data.begin() + range.hi, q)->key << std::endl;
```

**Comment by authwork** [comment]
Thanks for your patience. :)

**Comment by gvinciguerra** [comment]
Again, happy to help! 😇

**Comment by authwork** [comment]
@gvinciguerra 
I have a test on ```CompressedPGMIndex```

```
    int number = 10000;
    std::vector<MyKeyVal> data(number);
    for(int i=0; i<number; i++){
        data[i].key = i;
        data[i].val = "";
        for(int j=0; j<i; j++){
            data[i].val = data[j].val + "1";
        }
    }
    const int e = 128;
    auto q = 126;

    pgm::CompressedPGMIndex<decltype(MyKeyVal::key), e> c_index(data.begin(), data.end());
    auto range = c_index.search(q);
    auto lo = data.begin() + range.lo;
    auto hi = data.end() + range.hi;
    std::cout << std::lower_bound(lo, hi, q)->val.size() << std::endl;
```
And "Segmentation fault" appears. Using gdb to find:
```
0x000055555555d508 in std::vector<unsigned int, std::allocator<unsigned int> >::size() const ()
(gdb) bt
#0  0x000055555555d508 in std::vector<unsigned int, std::allocator<unsigned int> >::size() const ()
#1  0x0000555555562ee0 in pgm::CompressedPGMIndex<unsigned int, 128ul, 4ul, float>::CompressedLevel::size() const ()
#2  0x000055555555f130 in pgm::CompressedPGMIndex<unsigned int, 128ul, 4ul, float>::search(unsigned int const&) const
    ()
#3  0x000055555555ac17 in main ()
```

**Comment by gvinciguerra** [comment]
It should be

```cpp
auto hi = data.begin() + range.hi;
```

instead of

```cpp
auto hi = data.end() + range.hi;
```

**Comment by authwork** [comment]
Sorry for my carelessness, it should be ```auto hi = data.begin() + range.hi;```
But the issue still appears, I guess it happens when ```c_index.search(q)``` (from gdb info)

**Comment by gvinciguerra** [comment]
Thank you so much. It was a bug that should be fixed now.
Please note that `CompressedPGMIndex` does not compress anything in that case, because the keys are `0,1,2,..., 9999` and only one segment is produced.

**Comment by authwork** [comment]
Thanks for your help :)
Should I use ```pgm::internal::make_segmentation``` to create segments before using ```CompressedPGMIndex```. Is there any examples that can illustrate the size reduction when using ```CompressedPGMIndex```?
May it be able to combine ```CompressedPGMIndex``` with ```dynamicPGMIndex``` because I observe that, sometimes, the size of ```dynamicPGMIndex``` is far larger than ```PGMIndex```?

**Comment by gvinciguerra** [comment]
My pleasure 😉

Let me list some observations that should answer your doubts:

1. What `CompressedPGMIndex` does is to reduce the space taken by the segments of a `PGMIndex`. This is beneficial when `PGMIndex` outputs many many segments for a given `Epsilon` parameter (let's say when [`size_in_bytes()`](https://pgm.di.unipi.it/docs/cpp-reference/#classpgm_1_1_p_g_m_index_1a6184eab2f7e59153bfa93bcbb658237d) is hundreds or thousands of megabytes).
2. If you want to inspect the number of segments, you can call [`segments_count()`](https://pgm.di.unipi.it/docs/cpp-reference/#classpgm_1_1_p_g_m_index_1ab31ba6049ebca19dc403ac93b44de975) on a `PGMIndex` instance (the same method is available on `EliasFanoPGMIndex` and `BucketingPGMIndex` instances, which are simple variants of the `PGMIndex` that use different mechanisms to index the segments). So there's no need to call `pgm::internal::make_segmentation`.
3. Since `DynamicPGMIndex` is a container (i.e. data + index), its [`size_in_bytes()`](https://pgm.di.unipi.it/docs/cpp-reference/#classpgm_1_1_dynamic_p_g_m_index_1a3dd62ecf5517fb2255a168a60d189a48) methods returns the sum of the space taken by the data and the internal `PGMIndex`. This may be the reason why you notice that the size of `DynamicPGMIndex` is larger. It's because you are considering also the space taken by the data. If you want to see just the size of the internal index of `DynamicPGMIndex` you can call [`index_size_in_bytes()`](https://pgm.di.unipi.it/docs/cpp-reference/#classpgm_1_1_dynamic_p_g_m_index_1a09d5917adc5da39d026e6d292307131a).
4. You can switch the kind of PGM-index used in `DynamicPGMIndex` by providing it as the third template argument. For instance, you can replace [this line of the updates.cpp example](https://github.com/gvinciguerra/PGM-index/blob/08ddad4163fe02cf5e32dc34427a1ff9ca50010b/examples/updates.cpp#L22) with `pgm::DynamicPGMIndex<uint32_t, uint32_t, pgm::CompressedPGMIndex<uint32_t, 32>> dynamic_pgm(data.begin(), data.end());`. But keep in mind that this may not be beneficial, as the above point 1 explains.

**Comment by authwork** [comment]
Thanks, these observations and suggestions are very helpful. :)

**Comment by authwork** [comment]
@gvinciguerra 
Me again!
I want to conduct a new application for using PGM-index.
I want to create a map structure (i.e., key-only, without value). I think it can also use PGMIndex in the format of <Key Type, None Type>. 
For each time, I want to insert a element (so-called key) into the set, I will first search the index of such element. If cannot find, I insert the element (key), else do nothing.

How can I implement this map data structure by using PGM-index?

Many thanks!

**Comment by gvinciguerra** [comment]
You could use `pgm::DynamicPGMIndex<Key Type, bool>` and ignore the `bool` value associated with each key. Of course, you will pay 1 byte per element due to the unused bool value. To avoid the waste of space, you can try to edit the `DynamicPGMIndex` class to work with vectors of `Key Type` instead of vectors of pairs `<Key Type, Value Type>`.

The clean solution would be to refactor the logic of `pgm::DynamicPGMIndex` into one base class and then use this base class to implement a `set`-like and a `map`-like container. I'll put this on my to-do list.
