### ISSUE TITLE
Question: In which case should the DynamicPGMIndex be used?

### ISSUE THREAD

**Issue by yangzq50** [gvinciguerra/PGM-index#51]
According to https://pgm.di.unipi.it/ , the DynamicPGMIndex Predecessor query complexity is less effective than normal std::map ?

**Comment by gvinciguerra** [comment]
The `std::map` is usually implemented as a red-black tree, which incurs in $O(\log n)$ I/Os during a single query. Instead, the number of I/Os for a query with the `DynamicPGMIndex` is **a factor $O(\log B)$ lower,** where $B$ is the block size (assuming the `PGMIndex`es it uses internally fit in main memory). [Have a look at here](https://pgm.di.unipi.it/docs/computational-complexities/) for further details.

The `std::map` also consumes **much memory** since each element is stored in a node with [three pointers and one int for the color](https://github.com/gcc-mirror/gcc/blob/cf5f7791056b3ed993bc8024be767a86157514a9/libstdc%2B%2B-v3/include/bits/stl_tree.h#L102) (+32 bytes of overhead per element). Instead, the `DynamicPGMIndex` has an overhead of no more than ~`sizeof(PGMIndex<...>::Segment)`/`2*Epsilon` bytes per element (e.g. ≤ 20/32=0.625 byte per element if the key type is `int64` and `Epsilon=16`) .

Theory aside, my suggestion is to choose which one to use by experimenting with both of them on your application, input data, and query/insertion workload (possibly testing different [configuration parameters](https://github.com/gvinciguerra/PGM-index/blob/5e4c7086164d0f04ea4062f762f296dbd070ef40/include/pgm/pgm_index_dynamic.hpp#L161)).
